server:
  port: 8080
  tomcat:
    accept-count: 1000
    max-connections: 1000


spring:
    datasource:
        url: jdbc:mysql://123.56.52.20:3306/shy?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&relaxAutoCommit=true&serverTimezone=Asia/Shanghai
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    security:
        user:
            name: root
            password: root
    thymeleaf:
        prefix: classpath:static/htmls/

logging:
  level:
    '[org.springframework.web.servlet.DispatcherServlet]':  error
    '[com.shy]':  debug

Loggers:
    Root:
      level: error
      AppenderRef:
        - ref: FILE
        - ref: CONSOLEY

    Logger:
      - name: com.migu.spm
        additivity: false
        level: debug
        AppenderRef:
          - ref: FILE
          - ref: CONSOLE


